import type { Metadata } from "next";
import { LegalNotice } from "@/components/layout/legal-notice";
import { PageHeader } from "@/components/layout/page-header";

export const metadata: Metadata = {
  title: "Disclaimers — ScoreWell",
};

export default function DisclaimersPage() {
  return (
    <main className="flex flex-1 flex-col bg-surface">
      <div className="mx-auto w-full max-w-2xl px-4 py-16 sm:px-6 lg:px-8">
        <PageHeader title="Disclaimers" description="Last updated: August 24, 2026" />
        <LegalNotice />

        <div className="flex flex-col gap-6 text-ink-body">
          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Not an official test provider</h2>
            <p>
              ScoreWell is an independent prep platform. We are not
              affiliated with, endorsed by, or a reseller for the British
              Council, IDP: IELTS Australia, or Cambridge Assessment English,
              who jointly administer the official IELTS exam.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">AI feedback is an estimate</h2>
            <p>
              Band scores, corrections, and feedback generated by our AI
              tools are estimates based on common scoring criteria. They are
              not produced or endorsed by official examiners, and your actual
              exam result may differ.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Practice content</h2>
            <p>
              Practice tests and sample answers are written to reflect the
              style and difficulty of the real exam but are not official past
              papers unless explicitly stated.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-lg font-semibold text-ink">Community submissions</h2>
            <p>
              User-submitted answers and community feedback reflect the
              opinions of individual learners, not ScoreWell&apos;s
              assessment.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
