import type { SpeakingSeed } from "./speaking";

/**
 * Generated by ielts_pipeline (`generate`), converted from its website export.
 * Regenerate by re-running the pipeline's export + this conversion; do not hand-edit
 * content that should instead be fixed at the source and reconverted.
 */
export const SPEAKING_TESTS_GENERATED: SpeakingSeed[] = [
  {
    "slug": "generated-speaking-p1-0001",
    "title": "Part 1: Hometowns",
    "part": "part1",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-1",
      "hometowns"
    ],
    "data": {
      "questions": [
        "What is the name of the town or city where you grew up?",
        "What do you usually do when you have free time in your hometown?",
        "How has your hometown changed since you were a child?",
        "Is there a particular place in your hometown that you like to visit often?",
        "Do you think you would like to live in your hometown permanently?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0005",
    "title": "Part 1: Travel and transport",
    "part": "part1",
    "topic": "Travel and transport",
    "tags": [
      "speaking",
      "part-1",
      "travel-and-transport"
    ],
    "data": {
      "questions": [
        "How often do you travel by public transport?",
        "What is your preferred way of getting around your city?",
        "Can you describe a recent journey you enjoyed?",
        "Do you think travelling by train is more comfortable than traveling by bus?",
        "How has your travel routine changed in the last few years?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0007",
    "title": "Part 1: Food and cooking",
    "part": "part1",
    "topic": "Food and cooking",
    "tags": [
      "speaking",
      "part-1",
      "food-and-cooking"
    ],
    "data": {
      "questions": [
        "What is your typical breakfast on a weekday, and why do you choose it?",
        "How often do you cook meals at home instead of eating out?",
        "What is a dish you enjoy preparing for your family or friends?",
        "Do you have any food allergies or dietary restrictions that affect your cooking habits?",
        "When you have limited time, what quick meals do you usually make?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0010",
    "title": "Part 1: Food and cooking",
    "part": "part1",
    "topic": "Food and cooking",
    "tags": [
      "speaking",
      "part-1",
      "food-and-cooking"
    ],
    "data": {
      "questions": [
        "What is a typical breakfast you usually have on weekdays?",
        "How often do you cook meals at home instead of eating out?",
        "What type of cuisine do you enjoy the most and why?",
        "Do you have any food allergies or dietary restrictions that affect your cooking?",
        "When you have guests over, what dish do you like to prepare for them?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0013",
    "title": "Part 1: Work and study routines",
    "part": "part1",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-1",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "What time do you usually start your work or study day?",
        "Do you prefer to work/study in a quiet environment or with some background noise?",
        "How do you usually take breaks during a busy day?",
        "Do you often combine work tasks with studying for a course or qualification?",
        "What is your favourite activity to do after you finish work or study for the day?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0016",
    "title": "Part 1: The natural environment",
    "part": "part1",
    "topic": "The natural environment",
    "tags": [
      "speaking",
      "part-1",
      "the-natural-environment"
    ],
    "data": {
      "questions": [
        "Do you often spend time outdoors in natural settings such as parks or countryside?",
        "What kind of natural scenery do you enjoy most in your daily life?",
        "How do you usually travel to a natural location when you want to visit one?",
        "Do you think the natural environment in your city has changed in the last few years?",
        "What small actions do you take at home to help protect the natural environment?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0019",
    "title": "Part 1: Technology in daily life",
    "part": "part1",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-1",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "How often do you use a smartphone during a typical day?",
        "What kind of technology do you rely on most when you are at home?",
        "Do you prefer using a laptop or a tablet for reading e‐books, and why?",
        "Has your use of social media changed in the past few years?",
        "When you travel, what piece of technology do you find most useful?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0022",
    "title": "Part 1: The natural environment",
    "part": "part1",
    "topic": "The natural environment",
    "tags": [
      "speaking",
      "part-1",
      "the-natural-environment"
    ],
    "data": {
      "questions": [
        "How often do you spend time outdoors in natural settings?",
        "What kind of natural places do you enjoy visiting near your home?",
        "Have you noticed any changes in the environment where you live over the past few years?",
        "Do you have any habits that help protect the natural environment?",
        "How do you feel when you see polluted or littered areas?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0025",
    "title": "Part 1: Music",
    "part": "part1",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-1",
      "music"
    ],
    "data": {
      "questions": [
        "Do you often listen to music while you are traveling?",
        "What type of music do you usually choose when you are working or studying?",
        "Do you prefer listening to music alone or with other people?",
        "How has your taste in music changed over the past few years?",
        "Do you ever use music to improve your mood when you feel stressed?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0028",
    "title": "Part 1: Music",
    "part": "part1",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-1",
      "music"
    ],
    "data": {
      "questions": [
        "How often do you listen to music in a typical week?",
        "Where do you usually listen to music?",
        "Do you prefer listening to music alone or with others? Why?",
        "What type of music do you enjoy when you are exercising?",
        "Have you ever bought a musical instrument or taken lessons? Tell me about it."
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0031",
    "title": "Part 1: Technology in daily life",
    "part": "part1",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-1",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "How often do you use a smartphone during a typical day?",
        "What piece of technology do you rely on most at home?",
        "Do you prefer to shop online or in physical stores? Why?",
        "How has technology changed the way you keep in touch with friends?",
        "Are there any gadgets you would like to stop using? Explain."
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0034",
    "title": "Part 1: Hometowns",
    "part": "part1",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-1",
      "hometowns"
    ],
    "data": {
      "questions": [
        "What is the name of the town or city where you grew up?",
        "How would you describe the atmosphere of your hometown to someone who has never visited?",
        "Is there a particular street or neighbourhood in your hometown that you like to spend time in?",
        "What kinds of activities do people usually do for leisure in your hometown?",
        "Has your hometown changed much since you were a child, and if so, how?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0037",
    "title": "Part 1: Hometowns",
    "part": "part1",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-1",
      "hometowns"
    ],
    "data": {
      "questions": [
        "What is the name of the town or city where you grew up?",
        "Can you describe a typical street in your hometown?",
        "What kinds of shops or services are most common there?",
        "Do you think your hometown has changed much in the last ten years? Why or why not?",
        "Is there any place in your hometown you like to visit when you need to relax?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0040",
    "title": "Part 1: Work and study routines",
    "part": "part1",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-1",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "How do you usually organise your work or study tasks at the start of each day?",
        "What time of day do you feel most productive for studying or working, and why?",
        "Do you prefer to work or study in a quiet environment or with some background noise?",
        "How often do you take breaks during a typical work or study session?",
        "Has your daily routine changed significantly in the past few years? If so, how?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0043",
    "title": "Part 1: Travel and transport",
    "part": "part1",
    "topic": "Travel and transport",
    "tags": [
      "speaking",
      "part-1",
      "travel-and-transport"
    ],
    "data": {
      "questions": [
        "How often do you use public transport in your daily life?",
        "What is your preferred mode of travel for short trips and why?",
        "Can you describe a recent journey you made using a bicycle or walking?",
        "Do you usually plan your travel routes in advance or decide spontaneously?",
        "How do you feel about travelling during peak hours?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0046",
    "title": "Part 1: Hometowns",
    "part": "part1",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-1",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Can you tell me the name of the town or city where you grew up?",
        "What is your favourite place in your hometown and why?",
        "How has your hometown changed since you were a child?",
        "Do you think most people in your hometown still live there for a long time?",
        "Is there anything you would like to change about your hometown?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0049",
    "title": "Part 1: Technology in daily life",
    "part": "part1",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-1",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "How often do you use a smartphone in a typical day?",
        "What type of technology do you rely on most when you are at home?",
        "Can you recall a recent situation where a piece of technology made a task easier for you?",
        "Do you prefer using digital devices for entertainment or for communication, and why?",
        "How has the way you shop changed because of technology?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0052",
    "title": "Part 1: Work and study routines",
    "part": "part1",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-1",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "What time do you usually start your work or study day?",
        "How do you decide which tasks to do first in the morning?",
        "Do you take regular breaks during your work or study sessions, and if so, what do you do during those breaks?",
        "What is the most challenging part of balancing work and study for you?",
        "Do you have any habits that help you switch off from work or study at the end of the day?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0055",
    "title": "Part 1: Friends and celebrations",
    "part": "part1",
    "topic": "Friends and celebrations",
    "tags": [
      "speaking",
      "part-1",
      "friends-and-celebrations"
    ],
    "data": {
      "questions": [
        "How often do you meet up with your close friends?",
        "What kinds of celebrations do you usually attend with your friends?",
        "Can you tell me about a recent birthday party you went to?",
        "Do you prefer small gatherings or large parties? Why?",
        "How do you usually keep in touch with friends who live far away?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0058",
    "title": "Part 1: Music",
    "part": "part1",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-1",
      "music"
    ],
    "data": {
      "questions": [
        "Do you usually listen to music while you are doing household chores?",
        "What type of music do you prefer to start your day?",
        "How often do you go to concerts or live music performances?",
        "Do you play any musical instrument yourself?",
        "Has the kind of music you enjoy changed compared with when you were a teenager?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0061",
    "title": "Part 1: Technology in daily life",
    "part": "part1",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-1",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "How often do you use a smartphone during a typical day?",
        "What kinds of technology do you rely on at home?",
        "Do you prefer using digital calendars or paper ones? Why?",
        "Have you ever taken a break from using electronic devices? How did you feel?",
        "In what ways has technology changed the way you communicate with friends?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0064",
    "title": "Part 1: Friends and celebrations",
    "part": "part1",
    "topic": "Friends and celebrations",
    "tags": [
      "speaking",
      "part-1",
      "friends-and-celebrations"
    ],
    "data": {
      "questions": [
        "Do you usually spend your free time with friends?",
        "How often do you celebrate birthdays with your friends?",
        "What kind of activities do you enjoy doing with friends during holidays?",
        "Do you prefer small gatherings or large parties with friends?",
        "Has the way you celebrate with friends changed as you got older?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p3-0001",
    "title": "Part 3: Hometowns",
    "part": "part3",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-3",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Do you think people's sense of belonging to their hometown is stronger in some cultures than others?",
        "How important is it for a city to preserve its historical character while developing modern infrastructure?",
        "In what ways can migration from rural hometowns to big cities affect the social fabric of both places?",
        "Should governments invest more in improving the quality of life in smaller towns to reduce urban overcrowding?",
        "What role do hometown memories play in shaping an individual's identity as they move abroad?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0005",
    "title": "Part 3: Travel and transport",
    "part": "part3",
    "topic": "Travel and transport",
    "tags": [
      "speaking",
      "part-3",
      "travel-and-transport"
    ],
    "data": {
      "questions": [
        "What are the main factors that influence people's choice of transport in modern societies?",
        "How do you think advancements in technology will change long‐distance travel in the next 50 years?",
        "To what extent should governments invest in public transport versus road infrastructure?",
        "In what ways can tourism be balanced with environmental sustainability?",
        "How does the way people travel reflect cultural values and social status?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0007",
    "title": "Part 3: Food and cooking",
    "part": "part3",
    "topic": "Food and cooking",
    "tags": [
      "speaking",
      "part-3",
      "food-and-cooking"
    ],
    "data": {
      "questions": [
        "Do you think home cooking is becoming more or less popular in modern societies, and what factors influence this trend?",
        "How might the way people learn to cook change with advances in technology and online media?",
        "In what ways can cooking skills contribute to a person's health and wellbeing throughout their life?",
        "Should schools incorporate cooking lessons into their curricula, and what benefits could this bring to students?",
        "How do cultural traditions surrounding food and cooking shape national identity and social cohesion?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0010",
    "title": "Part 3: Food and cooking",
    "part": "part3",
    "topic": "Food and cooking",
    "tags": [
      "speaking",
      "part-3",
      "food-and-cooking"
    ],
    "data": {
      "questions": [
        "Do you think the ability to cook is becoming less important in today's fast‐paced society?",
        "How have changes in technology influenced the way people shop for and prepare food?",
        "What impact does home cooking have on family relationships and community bonds?",
        "Should schools incorporate cooking classes into their curricula, and what benefits might that bring?",
        "In what ways might cultural traditions around food be preserved or altered in a globalised world?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0013",
    "title": "Part 3: Work and study routines",
    "part": "part3",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-3",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "In what ways can employers support employees who are also pursuing further education?",
        "How might technology influence the way people manage their work and study routines in the future?",
        "Do you think flexible working hours improve overall learning outcomes for students who work part‐time?",
        "What are the potential social consequences if a large proportion of the population regularly juggles work and study?",
        "How does the culture of lifelong learning affect the traditional separation between work and education?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0016",
    "title": "Part 3: The natural environment",
    "part": "part3",
    "topic": "The natural environment",
    "tags": [
      "speaking",
      "part-3",
      "the-natural-environment"
    ],
    "data": {
      "questions": [
        "What role should governments play in preserving natural habitats and biodiversity?",
        "How can education influence people's attitudes toward the natural environment?",
        "In what ways can urban development be balanced with the need to protect green spaces?",
        "Do you think technological innovation can replace the functions of natural ecosystems?",
        "What are the biggest challenges societies face when trying to adopt more sustainable lifestyles?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0019",
    "title": "Part 3: Technology in daily life",
    "part": "part3",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-3",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "In what ways has the constant presence of digital devices affected people's ability to concentrate on tasks?",
        "Do you think the benefits of smart home appliances outweigh the potential privacy concerns they raise?",
        "How might reliance on technology influence interpersonal relationships in the long term?",
        "Should schools integrate emerging technologies into their curricula, and what challenges could this create?",
        "What responsibilities do technology companies have in ensuring that their products do not exacerbate social inequalities?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0022",
    "title": "Part 3: The natural environment",
    "part": "part3",
    "topic": "The natural environment",
    "tags": [
      "speaking",
      "part-3",
      "the-natural-environment"
    ],
    "data": {
      "questions": [
        "In what ways can individuals contribute to preserving natural ecosystems?",
        "How effective are government policies compared with community initiatives in protecting the environment?",
        "What role does education play in shaping people's attitudes toward nature?",
        "Do you think economic development should ever be prioritized over environmental conservation? Why or why not?",
        "How might climate change alter people's relationship with the natural environment in the future?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0025",
    "title": "Part 3: Music",
    "part": "part3",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-3",
      "music"
    ],
    "data": {
      "questions": [
        "In what ways can music reflect the cultural identity of a community?",
        "Do you think governments should invest more in music education in schools? Why or why not?",
        "How can popular music affect the attitudes and behaviours of young people?",
        "Is it possible for music to serve as a form of protest or political expression? If so, give examples of how this happens.",
        "What role does technology play in shaping the future of music consumption and creation?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0028",
    "title": "Part 3: Music",
    "part": "part3",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-3",
      "music"
    ],
    "data": {
      "questions": [
        "In what ways can music influence people's moods and behavior?",
        "Do you think that governments should support musicians and music education? Why or why not?",
        "How has technology changed the way we create and share music?",
        "To what extent can music be used as a tool for social or political change?",
        "Do you believe that the value of live performances will survive in the age of streaming? Why?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0031",
    "title": "Part 3: Technology in daily life",
    "part": "part3",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-3",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "In what ways has the widespread use of personal devices impacted people's attention spans?",
        "How might reliance on digital assistants change the skills that future generations develop?",
        "Do you think governments should regulate the amount of data collected by everyday appliances? Why or why not?",
        "How could increased automation in households influence employment patterns in the wider economy?",
        "What ethical considerations arise when technology is used to monitor personal health continuously?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0034",
    "title": "Part 3: Hometowns",
    "part": "part3",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-3",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Do you think people's sense of belonging to their hometown is becoming weaker or stronger in modern societies?",
        "In what ways can a hometown influence a person's values, habits, or worldview?",
        "How do migration patterns affect the cultural identity of a hometown?",
        "Should local governments invest more in preserving historic parts of a hometown, or focus on developing new infrastructure?",
        "What role do hometown memories play in shaping an individual's future aspirations or decisions?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0037",
    "title": "Part 3: Hometowns",
    "part": "part3",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-3",
      "hometowns"
    ],
    "data": {
      "questions": [
        "How do people's memories of their hometown influence their identity?",
        "What impact does rapid urban development have on the character of historic towns?",
        "In what ways can local governments preserve the cultural heritage of a hometown while encouraging modernization?",
        "Do you think people are more likely to move away from their hometowns now than in the past? Why?",
        "How might technology change the way people stay connected to their hometowns after they have moved elsewhere?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0040",
    "title": "Part 3: Work and study routines",
    "part": "part3",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-3",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "In what ways do flexible working hours influence employee well‐being and productivity on a societal level?",
        "How might the rise of online learning platforms affect traditional classroom education in the long term?",
        "Do you think governments should regulate the balance between work and study commitments for students? Why or why not?",
        "What role does technology play in shaping the boundaries between personal life and professional or academic responsibilities?",
        "Can a culture that values constant productivity be detrimental to creativity and mental health? Discuss."
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0043",
    "title": "Part 3: Travel and transport",
    "part": "part3",
    "topic": "Travel and transport",
    "tags": [
      "speaking",
      "part-3",
      "travel-and-transport"
    ],
    "data": {
      "questions": [
        "In what ways do you think the availability of fast and cheap transport influences people's choice of where to live?",
        "How might the increase in electric vehicles affect urban planning and public transport systems?",
        "Do you believe that tourism driven by easy travel has more positive or negative impacts on local cultures?",
        "What are the potential environmental consequences if air travel continues to grow at its current rate?",
        "How should governments balance the need for efficient transport infrastructure with the preservation of historic neighborhoods?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0046",
    "title": "Part 3: Hometowns",
    "part": "part3",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-3",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Do you think people's attachment to their hometown influences their identity? Why or why not?",
        "In what ways can hometowns affect a person's career choices or opportunities?",
        "How do migration patterns impact the development of smaller towns and larger cities?",
        "Should governments invest more in preserving the cultural heritage of hometowns? Discuss.",
        "What are the potential advantages and disadvantages of people moving away from their hometowns in today's globalised world?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0049",
    "title": "Part 3: Technology in daily life",
    "part": "part3",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-3",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "In what ways has the increasing presence of technology in daily routines affected people's social relationships?",
        "Do you think reliance on technology improves efficiency at the cost of personal creativity? Why or why not?",
        "How might widespread use of smart devices impact the privacy of individuals in society?",
        "Should schools teach students how to manage and limit their use of technology? Explain your view.",
        "What are the potential long‐term effects on health if people continue to depend heavily on technology for everyday tasks?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0052",
    "title": "Part 3: Work and study routines",
    "part": "part3",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-3",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "In your opinion, how does the rise of remote work and online learning influence people's ability to manage work‐study routines?",
        "Do you think that having a fixed daily routine is more beneficial than a flexible one for people who are both working and studying?",
        "What role should employers and educational institutions play in supporting individuals who are juggling work and study?",
        "How might cultural attitudes toward work and education shape the way people structure their daily routines?",
        "Do you foresee any long‐term societal changes if more people adopt hybrid work‐study schedules in the future?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0055",
    "title": "Part 3: Friends and celebrations",
    "part": "part3",
    "topic": "Friends and celebrations",
    "tags": [
      "speaking",
      "part-3",
      "friends-and-celebrations"
    ],
    "data": {
      "questions": [
        "In what ways do celebrations strengthen friendships within a community?",
        "Do you think modern technology has changed the way people celebrate together? How?",
        "How important is it for societies to preserve traditional celebrations, and what role do friends play in that?",
        "Some people argue that large public festivals can exclude certain groups. What is your view on inclusivity in celebrations?",
        "How might the increasing focus on individualism affect the future of communal celebrations?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0058",
    "title": "Part 3: Music",
    "part": "part3",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-3",
      "music"
    ],
    "data": {
      "questions": [
        "In what ways can music shape a nation's cultural identity?",
        "Do you think music education should be a compulsory part of school curricula, and why?",
        "How have digital streaming platforms changed the relationship between listeners and musicians?",
        "Should governments intervene to regulate the content of popular music, for example to limit explicit lyrics?",
        "Can music be an effective tool for social or political protest, and can you give examples?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0061",
    "title": "Part 3: Technology in daily life",
    "part": "part3",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-3",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "To what extent should governments regulate the development of personal technology?",
        "How might reliance on digital devices impact people's ability to think critically?",
        "In what ways could technology reshape social relationships in the next decade?",
        "Do you think the benefits of constant connectivity outweigh the potential drawbacks for society? Why or why not?",
        "How can individuals balance the convenience of technology with the need for privacy and security?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0064",
    "title": "Part 3: Friends and celebrations",
    "part": "part3",
    "topic": "Friends and celebrations",
    "tags": [
      "speaking",
      "part-3",
      "friends-and-celebrations"
    ],
    "data": {
      "questions": [
        "Why do people tend to organize celebrations with friends rather than alone?",
        "In what ways can celebrating together strengthen friendships in a community?",
        "How do cultural differences influence the way friends celebrate milestones?",
        "Do you think modern technology has changed the nature of celebrations among friends?",
        "What responsibilities, if any, should friends have towards each other when planning a celebration?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p2-0001",
    "title": "Part 2: Describe your hometown",
    "part": "part2",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-2",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Describe your hometown"
      ],
      "cueCardPoints": [
        "where it is located and its surroundings",
        "the main features or landmarks that define it",
        "the activities you enjoy doing there",
        "and explain how living there has influenced your outlook on life"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0005",
    "title": "Part 2: Describe a memorable journey you took using an unusual mode of transport.",
    "part": "part2",
    "topic": "Travel and transport",
    "tags": [
      "speaking",
      "part-2",
      "travel-and-transport"
    ],
    "data": {
      "questions": [
        "Describe a memorable journey you took using an unusual mode of transport."
      ],
      "cueCardPoints": [
        "where you went",
        "why you chose that mode of transport",
        "what you experienced during the trip",
        "and explain how the journey affected your view of travel"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0007",
    "title": "Part 2: Describe a memorable meal that you have cooked yourself",
    "part": "part2",
    "topic": "Food and cooking",
    "tags": [
      "speaking",
      "part-2",
      "food-and-cooking"
    ],
    "data": {
      "questions": [
        "Describe a memorable meal that you have cooked yourself"
      ],
      "cueCardPoints": [
        "What the occasion was and why you decided to cook the meal",
        "The main ingredients and the cooking methods you used",
        "How the meal turned out and the reactions of the people who ate it",
        "and explain what made this particular cooking experience stand out for you"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0010",
    "title": "Part 2: Describe a time when you prepared a special dish for someone",
    "part": "part2",
    "topic": "Food and cooking",
    "tags": [
      "speaking",
      "part-2",
      "food-and-cooking"
    ],
    "data": {
      "questions": [
        "Describe a time when you prepared a special dish for someone"
      ],
      "cueCardPoints": [
        "Who you prepared the dish for",
        "What the dish was and why it was special",
        "How you went about preparing and cooking it",
        "and explain why you chose that particular dish"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0013",
    "title": "Part 2: Describe a typical day when you balance work and study",
    "part": "part2",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-2",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "Describe a typical day when you balance work and study"
      ],
      "cueCardPoints": [
        "what your schedule looks like",
        "how you organize your tasks",
        "any challenges you face",
        "and explain how you keep yourself motivated"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0016",
    "title": "Part 2: Describe a natural place you have visited that left a strong impression on you.",
    "part": "part2",
    "topic": "The natural environment",
    "tags": [
      "speaking",
      "part-2",
      "the-natural-environment"
    ],
    "data": {
      "questions": [
        "Describe a natural place you have visited that left a strong impression on you."
      ],
      "cueCardPoints": [
        "where it is located",
        "what you did there",
        "what you noticed about the environment",
        "and explain why the experience was memorable"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0019",
    "title": "Part 2: Describe a piece of technology that you use regularly in your everyday life.",
    "part": "part2",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-2",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "Describe a piece of technology that you use regularly in your everyday life."
      ],
      "cueCardPoints": [
        "What the technology is and how you first obtained it",
        "How you typically use it throughout the day",
        "The ways in which it has made your life easier or more efficient",
        "and explain why this device has become essential for you"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0025",
    "title": "Part 2: Describe a piece of music that has a special meaning to you.",
    "part": "part2",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-2",
      "music"
    ],
    "data": {
      "questions": [
        "Describe a piece of music that has a special meaning to you."
      ],
      "cueCardPoints": [
        "When you first heard it and where you were",
        "What the music sounds like and the instruments you can hear",
        "Why this piece is important or memorable to you",
        "and explain how it has influenced your life or your outlook"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0028",
    "title": "Part 2: Describe a piece of music that has a special meaning for you.",
    "part": "part2",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-2",
      "music"
    ],
    "data": {
      "questions": [
        "Describe a piece of music that has a special meaning for you."
      ],
      "cueCardPoints": [
        "what the piece is and how you first heard it",
        "the circumstances in which you usually listen to it",
        "the emotions or memories it evokes",
        "and explain why it remains important to you."
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0031",
    "title": "Part 2: Describe a piece of technology that has become an essential part of your daily routine.",
    "part": "part2",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-2",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "Describe a piece of technology that has become an essential part of your daily routine."
      ],
      "cueCardPoints": [
        "What the technology is and how it works.",
        "When you first started using it.",
        "How it has affected your daily activities.",
        "and explain why you think it will remain important in the future."
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0034",
    "title": "Part 2: Describe a memorable place in your hometown that you like to visit or think about often.",
    "part": "part2",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-2",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Describe a memorable place in your hometown that you like to visit or think about often."
      ],
      "cueCardPoints": [
        "What the place is and where it is located in your hometown",
        "How you first discovered or became aware of this place",
        "Why this place is special or important to you",
        "and explain how this place reflects the overall character or spirit of your hometown"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0037",
    "title": "Part 2: Describe a place in your hometown that is special to you.",
    "part": "part2",
    "topic": "Hometowns",
    "tags": [
      "speaking",
      "part-2",
      "hometowns"
    ],
    "data": {
      "questions": [
        "Describe a place in your hometown that is special to you."
      ],
      "cueCardPoints": [
        "what the place is and where it is located",
        "how you first discovered or started visiting it",
        "what you usually do when you are there",
        "and explain why this place is important to you"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0040",
    "title": "Part 2: Describe a time when you had to adjust your work or study routine",
    "part": "part2",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-2",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "Describe a time when you had to adjust your work or study routine"
      ],
      "cueCardPoints": [
        "What the original routine was like",
        "Why you needed to make a change",
        "What steps you took to modify the routine",
        "and explain how the new routine impacted your overall performance"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0043",
    "title": "Part 2: Describe a memorable journey you made by train",
    "part": "part2",
    "topic": "Travel and transport",
    "tags": [
      "speaking",
      "part-2",
      "travel-and-transport"
    ],
    "data": {
      "questions": [
        "Describe a memorable journey you made by train"
      ],
      "cueCardPoints": [
        "where you travelled to",
        "who you travelled with",
        "what you experienced or did during the trip",
        "and explain why this journey was significant to you"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0052",
    "title": "Part 2: Describe a typical day when you have to combine work and study responsibilities.",
    "part": "part2",
    "topic": "Work and study routines",
    "tags": [
      "speaking",
      "part-2",
      "work-and-study-routines"
    ],
    "data": {
      "questions": [
        "Describe a typical day when you have to combine work and study responsibilities."
      ],
      "cueCardPoints": [
        "what your schedule looks like from morning until evening",
        "how you organise and prioritise your tasks",
        "what tools, techniques or environments you use to stay focused",
        "and explain how this routine affects your overall productivity and well‐being"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0055",
    "title": "Part 2: Describe a memorable celebration you shared with a group of friends",
    "part": "part2",
    "topic": "Friends and celebrations",
    "tags": [
      "speaking",
      "part-2",
      "friends-and-celebrations"
    ],
    "data": {
      "questions": [
        "Describe a memorable celebration you shared with a group of friends"
      ],
      "cueCardPoints": [
        "who was there",
        "what was the occasion",
        "how you prepared for it",
        "and explain why it was memorable for you"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0058",
    "title": "Part 2: Describe a piece of music that has special meaning to you.",
    "part": "part2",
    "topic": "Music",
    "tags": [
      "speaking",
      "part-2",
      "music"
    ],
    "data": {
      "questions": [
        "Describe a piece of music that has special meaning to you."
      ],
      "cueCardPoints": [
        "What the piece of music is and who composed or performed it",
        "When you first heard it and the circumstances surrounding that first experience",
        "Why this piece is important or emotional for you",
        "and explain how it influences your thoughts or actions in everyday life"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0061",
    "title": "Part 2: Describe a piece of technology that you use regularly and find indispensable.",
    "part": "part2",
    "topic": "Technology in daily life",
    "tags": [
      "speaking",
      "part-2",
      "technology-in-daily-life"
    ],
    "data": {
      "questions": [
        "Describe a piece of technology that you use regularly and find indispensable."
      ],
      "cueCardPoints": [
        "what the device is and how you first obtained it",
        "the main functions you use it for",
        "how it has affected your daily routine",
        "and explain why you would find it difficult to live without it"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0064",
    "title": "Part 2: Describe a memorable celebration you shared with friends",
    "part": "part2",
    "topic": "Friends and celebrations",
    "tags": [
      "speaking",
      "part-2",
      "friends-and-celebrations"
    ],
    "data": {
      "questions": [
        "Describe a memorable celebration you shared with friends"
      ],
      "cueCardPoints": [
        "Who was involved in the celebration",
        "What the occasion was",
        "What activities you and your friends did during the celebration",
        "and explain why this celebration was particularly meaningful to you"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p1-0101",
    "title": "Part 1: Reading habits",
    "part": "part1",
    "topic": "Reading habits",
    "tags": ["speaking", "part-1", "reading-habits"],
    "data": {
      "questions": [
        "Do you enjoy reading in your free time?",
        "What kind of books or magazines do you usually read?",
        "Did you read a lot of books when you were a child?",
        "Do you prefer reading printed books or e-books?",
        "How has your reading habit changed over the years?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0102",
    "title": "Part 1: Sport and exercise",
    "part": "part1",
    "topic": "Sport and exercise",
    "tags": ["speaking", "part-1", "sport-and-exercise"],
    "data": {
      "questions": [
        "Do you play any sports?",
        "What sport did you enjoy when you were a child?",
        "How often do you exercise?",
        "Do you prefer exercising alone or with other people?",
        "Is sport popular where you live?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p1-0103",
    "title": "Part 1: Shopping",
    "part": "part1",
    "topic": "Shopping",
    "tags": ["speaking", "part-1", "shopping"],
    "data": {
      "questions": [
        "Do you enjoy shopping?",
        "How often do you go shopping for clothes?",
        "Do you prefer shopping online or in physical stores?",
        "What was the last thing you bought?",
        "Do you usually plan your purchases in advance, or buy things on impulse?"
      ],
      "guidance": "Answer each question naturally, extending your response beyond a single sentence where you can. Aim for two to four sentences per answer — long enough to show your range, short enough to stay conversational."
    }
  },
  {
    "slug": "generated-speaking-p2-0104",
    "title": "Part 2: Describe a book you would recommend to a friend",
    "part": "part2",
    "topic": "Reading habits",
    "tags": ["speaking", "part-2", "reading-habits"],
    "data": {
      "questions": ["Describe a book you would recommend to a friend"],
      "cueCardPoints": [
        "what the book is about",
        "when you read it",
        "why you would recommend it",
        "and explain how you think it might benefit the person you recommend it to"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0105",
    "title": "Part 2: Describe a sport or physical activity you would like to try",
    "part": "part2",
    "topic": "Sport and exercise",
    "tags": ["speaking", "part-2", "sport-and-exercise"],
    "data": {
      "questions": ["Describe a sport or physical activity you would like to try"],
      "cueCardPoints": [
        "what the sport or activity is",
        "why you have not tried it yet",
        "what you would need to do to try it",
        "and explain why you think you would enjoy it"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p2-0106",
    "title": "Part 2: Describe a memorable purchase you made",
    "part": "part2",
    "topic": "Shopping",
    "tags": ["speaking", "part-2", "shopping"],
    "data": {
      "questions": ["Describe a memorable purchase you made"],
      "cueCardPoints": [
        "what you bought",
        "where you bought it",
        "why you decided to buy it",
        "and explain how you felt about the purchase afterwards"
      ],
      "guidance": "You have 1 minute to prepare and should speak for 1–2 minutes. Use the preparation time to note four or five points, not one — running out early is a common way to lose marks."
    }
  },
  {
    "slug": "generated-speaking-p3-0107",
    "title": "Part 3: Reading in the modern world",
    "part": "part3",
    "topic": "Reading habits",
    "tags": ["speaking", "part-3", "reading-habits"],
    "data": {
      "questions": [
        "Do you think reading habits have changed in the age of smartphones and social media?",
        "What are the benefits of reading fiction compared to non-fiction?",
        "Should schools require students to read a certain number of books each year?",
        "Do you think audiobooks provide the same benefits as reading a physical book?",
        "How might libraries need to change to stay relevant in the future?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0108",
    "title": "Part 3: Sport in society",
    "part": "part3",
    "topic": "Sport and exercise",
    "tags": ["speaking", "part-3", "sport-and-exercise"],
    "data": {
      "questions": [
        "Why do you think some sports are more popular in certain countries than others?",
        "Should schools place more emphasis on physical education?",
        "Do you think professional athletes are paid too much?",
        "How has technology changed the way people train for sports?",
        "What role does sport play in bringing communities together?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  },
  {
    "slug": "generated-speaking-p3-0109",
    "title": "Part 3: Consumer culture and shopping",
    "part": "part3",
    "topic": "Shopping",
    "tags": ["speaking", "part-3", "shopping"],
    "data": {
      "questions": [
        "What are the advantages and disadvantages of online shopping compared to shopping in stores?",
        "Do you think advertising influences people to buy things they do not need?",
        "How has shopping changed in your country over the last twenty years?",
        "Should there be more regulation of how companies advertise to children?",
        "Do you think people today are more materialistic than in the past?"
      ],
      "guidance": "Part 3 answers should be developed and justified, not just stated. Give your view, explain the reasoning behind it, and where you can, acknowledge the counter-argument before resolving it."
    }
  }
];
