import type { WritingSeed } from "./writing";

/**
 * Generated by ielts_pipeline (`generate`), converted from its website export.
 * Regenerate by re-running the pipeline's export + this conversion; do not hand-edit
 * content that should instead be fixed at the source and reconverted.
 *
 * Exception: the `chart` field on each task1-academic item. The pipeline never emitted one —
 * every prompt said "the chart/map/table below" with no chart to show. Added by hand from the
 * prompt text until the pipeline itself is updated to generate chart data; a reconversion will
 * need to re-add these.
 */
export const WRITING_ITEMS_GENERATED: WritingSeed[] = [
  {
    "slug": "generated-writing-academic-task1-0001",
    "title": "Task 1: General (Map)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "map"
    ],
    "kind": "test",
    "data": {
      "prompt": "The map below shows the number of households owning a microwave oven (per 100 households) in five major cities in 1990 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the key changes and differences shown, in your own words. Do not give your opinion.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "bar",
        "unit": "per 100 households",
        "categories": ["Cairo", "Jakarta", "Lagos", "Mumbai", "São Paulo"],
        "series": [
          { "label": "1990", "values": [12, 18, 6, 15, 22] },
          { "label": "2020", "values": [64, 71, 38, 67, 79] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0003",
    "title": "Task 1: General (Pie chart)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "pie-chart"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the percentage distribution of different dating methods employed by archaeologists in 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "pie",
        "unit": "%",
        "slices": [
          { "label": "Radiocarbon dating", "value": 38 },
          { "label": "Stratigraphy", "value": 24 },
          { "label": "Dendrochronology", "value": 14 },
          { "label": "Thermoluminescence", "value": 11 },
          { "label": "Other methods", "value": 13 }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0004",
    "title": "Task 1: General (Table)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "table"
    ],
    "kind": "test",
    "data": {
      "prompt": "The table below shows the number of maps produced by the National Cartographic Agency for four different types of maps over a period of twenty years, recorded at five‐year intervals between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "table",
        "columns": ["2000", "2005", "2010", "2015", "2020"],
        "rows": [
          { "label": "Topographic maps", "values": [420, 390, 310, 240, 180] },
          { "label": "Road maps", "values": [310, 340, 280, 190, 120] },
          { "label": "Nautical charts", "values": [95, 110, 130, 150, 165] },
          { "label": "Digital-only maps", "values": [5, 60, 210, 480, 820] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0007",
    "title": "Task 1: Environment (Map)",
    "taskType": "task1-academic",
    "topic": "Environment",
    "tags": [
      "writing",
      "task-1",
      "environment",
      "map"
    ],
    "kind": "test",
    "data": {
      "prompt": "The map below shows the number of recycling collection points in each of five zones of Greentown in 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the key changes and differences shown, in your own words. Do not give your opinion.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "bar",
        "unit": "collection points",
        "categories": ["North", "East", "South", "West", "Central"],
        "series": [
          { "label": "2010", "values": [3, 5, 2, 4, 6] },
          { "label": "2020", "values": [14, 12, 9, 11, 20] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0008",
    "title": "Task 1: Technology (Line graph)",
    "taskType": "task1-academic",
    "topic": "Technology",
    "tags": [
      "writing",
      "task-1",
      "technology",
      "line-graph"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the number of printed topographic maps produced, digital map downloads, and satellite imagery layers added each year between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "line",
        "unit": "thousands per year",
        "xLabels": ["2000", "2005", "2010", "2015", "2020"],
        "series": [
          { "label": "Printed topographic maps", "values": [420, 380, 260, 140, 60] },
          { "label": "Digital map downloads", "values": [10, 90, 340, 720, 1150] },
          { "label": "Satellite imagery layers added", "values": [5, 40, 150, 400, 780] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0009",
    "title": "Task 1: General (Pie chart)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "pie-chart"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the proportion of different acoustic design elements used in the construction of contemporary concert halls worldwide in 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "pie",
        "unit": "%",
        "slices": [
          { "label": "Reflective panels", "value": 31 },
          { "label": "Sound diffusers", "value": 22 },
          { "label": "Absorptive material", "value": 19 },
          { "label": "Variable acoustic banners", "value": 15 },
          { "label": "Other elements", "value": 13 }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0010",
    "title": "Task 1: General (Table)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "table"
    ],
    "kind": "test",
    "data": {
      "prompt": "The table below shows the average number of individuals observed during the spring migration of four bird species in the years 2010, 2015 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "table",
        "columns": ["2010", "2015", "2020"],
        "rows": [
          { "label": "Arctic Tern", "values": [1250, 1080, 860] },
          { "label": "Barn Swallow", "values": [2100, 1950, 1700] },
          { "label": "Whooper Swan", "values": [340, 410, 470] },
          { "label": "Osprey", "values": [180, 230, 290] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0011",
    "title": "Task 1: General (Pie chart)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "pie-chart"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the proportion of different types of volcanic eruptions that occurred worldwide in 2022. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "pie",
        "unit": "%",
        "slices": [
          { "label": "Strombolian", "value": 34 },
          { "label": "Vulcanian", "value": 26 },
          { "label": "Effusive", "value": 18 },
          { "label": "Plinian", "value": 12 },
          { "label": "Phreatic", "value": 10 }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0012",
    "title": "Task 1: General (Table)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "table"
    ],
    "kind": "test",
    "data": {
      "prompt": "The table below shows the average retail price (in US dollars) of three common household items in four selected years. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "table",
        "columns": ["2000", "2010", "2020", "2024"],
        "rows": [
          { "label": "Electric kettle", "values": ["$18", "$22", "$27", "$31"] },
          { "label": "Vacuum cleaner", "values": ["$65", "$78", "$95", "$110"] },
          { "label": "Microwave oven", "values": ["$120", "$95", "$70", "$62"] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task1-0014",
    "title": "Task 1: Society (Line graph)",
    "taskType": "task1-academic",
    "topic": "Society",
    "tags": [
      "writing",
      "task-1",
      "society",
      "line-graph"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the proportion of total urban land in Metroville that was dedicated to green roofs, public parks, and community gardens between 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20,
      "chart": {
        "type": "line",
        "unit": "% of total urban land",
        "xLabels": ["2010", "2013", "2016", "2020"],
        "series": [
          { "label": "Green roofs", "values": [0.4, 0.9, 1.8, 3.1] },
          { "label": "Public parks", "values": [6.2, 6.5, 6.8, 7.3] },
          { "label": "Community gardens", "values": [0.8, 1.3, 2.0, 2.6] }
        ]
      }
    }
  },
  {
    "slug": "generated-writing-academic-task2-0001",
    "title": "Task 2: General",
    "taskType": "task2",
    "topic": "General",
    "tags": [
      "writing",
      "task-2",
      "general",
      "opinion"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some people claim that modern scientific dating techniques, such as radiocarbon dating, have rendered traditional archaeological methods obsolete. To what extent do you agree or disagree with this view? Give reasons for your answer and include any relevant examples from history or everyday life. Write at least 250 words.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0003",
    "title": "Task 2: Society",
    "taskType": "task2",
    "topic": "Society",
    "tags": [
      "writing",
      "task-2",
      "society",
      "problem-solution"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some people think that the historical significance of public libraries is being overlooked in modern societies, leading to reduced funding and usage. Discuss the main problems associated with this situation and suggest practical measures that could be taken to preserve and promote the role of public libraries in the community. Write at least 250 words.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0004",
    "title": "Task 2: Technology",
    "taskType": "task2",
    "topic": "Technology",
    "tags": [
      "writing",
      "task-2",
      "technology",
      "double-question"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some people argue that digital mapping technologies have rendered traditional paper maps obsolete, whereas others believe that paper maps still have important uses. Discuss both views and give your own opinion.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0012",
    "title": "Task 2: Environment",
    "taskType": "task2",
    "topic": "Environment",
    "tags": [
      "writing",
      "task-2",
      "environment",
      "double-question"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some governments are considering increasing investment in recycling programmes. Discuss the economic benefits that recycling can bring to a country, and suggest two practical measures that could be taken to make recycling more financially sustainable.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0014",
    "title": "Task 2: Technology",
    "taskType": "task2",
    "topic": "Technology",
    "tags": [
      "writing",
      "task-2",
      "technology",
      "discussion"
    ],
    "kind": "test",
    "data": {
      "prompt": "Public libraries have existed for centuries, but their relevance in modern society is debated. Some people argue that public libraries are essential because they provide free access to information, support lifelong learning, and serve as community hubs. Others claim that digital technology and online resources have made physical libraries obsolete, and that the funds used for libraries could be better spent elsewhere. Discuss both views and give your own opinion. (Write at least 250 words)",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  }
];
