import type { WritingSeed } from "./writing";

/**
 * Generated by ielts_pipeline (`generate`), converted from its website export.
 * Regenerate by re-running the pipeline's export + this conversion; do not hand-edit
 * content that should instead be fixed at the source and reconverted.
 */
export const WRITING_ITEMS_GENERATED: WritingSeed[] = [
  {
    "slug": "generated-writing-academic-task1-0001",
    "title": "Task 1: General (Map)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "map"
    ],
    "kind": "test",
    "data": {
      "prompt": "The map below shows the number of households owning a microwave oven (per 100 households) in five major cities in 1990 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the key changes and differences shown, in your own words. Do not give your opinion.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0003",
    "title": "Task 1: General (Pie chart)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "pie-chart"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the percentage distribution of different dating methods employed by archaeologists in 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0004",
    "title": "Task 1: General (Table)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "table"
    ],
    "kind": "test",
    "data": {
      "prompt": "The table below shows the number of maps produced by the National Cartographic Agency for four different types of maps over a period of twenty years, recorded at five‐year intervals between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0007",
    "title": "Task 1: Environment (Map)",
    "taskType": "task1-academic",
    "topic": "Environment",
    "tags": [
      "writing",
      "task-1",
      "environment",
      "map"
    ],
    "kind": "test",
    "data": {
      "prompt": "The map below shows the number of recycling collection points in each of five zones of Greentown in 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the key changes and differences shown, in your own words. Do not give your opinion.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0008",
    "title": "Task 1: Technology (Line graph)",
    "taskType": "task1-academic",
    "topic": "Technology",
    "tags": [
      "writing",
      "task-1",
      "technology",
      "line-graph"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the number of printed topographic maps produced, digital map downloads, and satellite imagery layers added each year between 2000 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0009",
    "title": "Task 1: General (Pie chart)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "pie-chart"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the proportion of different acoustic design elements used in the construction of contemporary concert halls worldwide in 2025. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0010",
    "title": "Task 1: General (Table)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "table"
    ],
    "kind": "test",
    "data": {
      "prompt": "The table below shows the average number of individuals observed during the spring migration of four bird species in the years 2010, 2015 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0011",
    "title": "Task 1: General (Pie chart)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "pie-chart"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the proportion of different types of volcanic eruptions that occurred worldwide in 2022. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0012",
    "title": "Task 1: General (Table)",
    "taskType": "task1-academic",
    "topic": "General",
    "tags": [
      "writing",
      "task-1",
      "general",
      "table"
    ],
    "kind": "test",
    "data": {
      "prompt": "The table below shows the average retail price (in US dollars) of three common household items in four selected years. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task1-0014",
    "title": "Task 1: Society (Line graph)",
    "taskType": "task1-academic",
    "topic": "Society",
    "tags": [
      "writing",
      "task-1",
      "society",
      "line-graph"
    ],
    "kind": "test",
    "data": {
      "prompt": "The chart below shows the proportion of total urban land in Metroville that was dedicated to green roofs, public parks, and community gardens between 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.",
      "instructions": "Describe the chart in your own words. Do not give your opinion, and do not speculate about causes the data does not show.",
      "minWords": 150,
      "minutes": 20
    }
  },
  {
    "slug": "generated-writing-academic-task2-0001",
    "title": "Task 2: General",
    "taskType": "task2",
    "topic": "General",
    "tags": [
      "writing",
      "task-2",
      "general",
      "opinion"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some people claim that modern scientific dating techniques, such as radiocarbon dating, have rendered traditional archaeological methods obsolete. To what extent do you agree or disagree with this view? Give reasons for your answer and include any relevant examples from history or everyday life. Write at least 250 words.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0003",
    "title": "Task 2: Society",
    "taskType": "task2",
    "topic": "Society",
    "tags": [
      "writing",
      "task-2",
      "society",
      "problem-solution"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some people think that the historical significance of public libraries is being overlooked in modern societies, leading to reduced funding and usage. Discuss the main problems associated with this situation and suggest practical measures that could be taken to preserve and promote the role of public libraries in the community. Write at least 250 words.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0004",
    "title": "Task 2: Technology",
    "taskType": "task2",
    "topic": "Technology",
    "tags": [
      "writing",
      "task-2",
      "technology",
      "double-question"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some people argue that digital mapping technologies have rendered traditional paper maps obsolete, whereas others believe that paper maps still have important uses. Discuss both views and give your own opinion.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0012",
    "title": "Task 2: Environment",
    "taskType": "task2",
    "topic": "Environment",
    "tags": [
      "writing",
      "task-2",
      "environment",
      "double-question"
    ],
    "kind": "test",
    "data": {
      "prompt": "Some governments are considering increasing investment in recycling programmes. Discuss the economic benefits that recycling can bring to a country, and suggest two practical measures that could be taken to make recycling more financially sustainable.",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  },
  {
    "slug": "generated-writing-academic-task2-0014",
    "title": "Task 2: Technology",
    "taskType": "task2",
    "topic": "Technology",
    "tags": [
      "writing",
      "task-2",
      "technology",
      "discussion"
    ],
    "kind": "test",
    "data": {
      "prompt": "Public libraries have existed for centuries, but their relevance in modern society is debated. Some people argue that public libraries are essential because they provide free access to information, support lifelong learning, and serve as community hubs. Others claim that digital technology and online resources have made physical libraries obsolete, and that the funds used for libraries could be better spent elsewhere. Discuss both views and give your own opinion. (Write at least 250 words)",
      "instructions": "Give reasons for your answer and include any relevant examples from your own knowledge or experience.",
      "minWords": 250,
      "minutes": 40
    }
  }
];
